baseURL = 'https://codeandcypher.com/'
title = 'Code and Cypher'
enableRobotsTXT = true
theme = "hugo-theme-m10c"
	
	
highlightjs = true


[params]
	googleAnalytics = "G-J61D2SEYHZ"
	author = "Joshua Wortz"
	description = "Code and Cypher explores the intersection of technology, cybersecurity, and automation."
	avatar = "/static/images/avatar.png"
	#menu_item_separator: Separator between each menu item. HTML allowed (default: " - “)
	#favicon = "C:\Users\joshu\Documents\codeandcypher\static\images\favicon.png"
	
[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"


# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/SixFiveMil"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/joshuawortz/"

[params.style]
darkestColor = "#062e04"
darkColor = "#343232"
lightColor = "#96782C"
lightestColor = "#f2e7c7"
primaryColor = "#ffffff"