baseURL = 'https://codeandcypher.com/'
title = 'Code and Cypher'
enableRobotsTXT = true
theme="beautifulhugo"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
	googleAnalytics = "G-J61D2SEYHZ"
	
# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/SixFiveMil"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/joshuawortz/"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

