name: Deploy to Bluehost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH Deployment
        # You may pin to the exact commit or the version.
        # uses: saranraj3195/sparkout-deployment@c4665eb5fc6ae732e5f15341125b89c3c96b9680
        uses: saranraj3195/sparkout-deployment@v2
        with:
          # SSH private key for authentication
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # SSH username
          USERNAME: dasmhrmy
          # IP address of the server
          SERVER_IP: 50.6.154.89
          # SSH port of the server
          SERVER_PORT: 22
          # Destination directory on the server
          SERVER_DESTINATION: ~/public_html
          # Additional rsync arguments
          #ARGS: # optional
          # Folder to deploy
          FOLDER: /public
                
